### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by devlee** [i5ting/kv2#1]
After build && start, I got it:

> server started at http://localhost:3000
> data pre-fetch: 36ms
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write after end
>     at ServerResponse.write (_http_outgoing.js:443:15)
>     at Object.ctx.write (C:\github\vuekoassr\koa2vue2ssr\node_modules\koa-bigpipe\index.js:31:9)
>     at PassThrough.renderStream.on.chunk (C:\github\vuekoassr\koa2vue2ssr\server.js:75:13)
>     at emitOne (events.js:96:13)
>     at PassThrough.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at PassThrough.Readable.push (_stream_readable.js:134:10)
>     at PassThrough.Transform.push (_stream_transform.js:128:32)
>     at afterTransform (_stream_transform.js:77:12)
>     at TransformState.afterTransform (_stream_transform.js:54:12)
> 
> npm ERR! Windows_NT 10.0.15014
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
> npm ERR! node v7.2.0
> npm ERR! npm  v3.10.9
> npm ERR! code ELIFECYCLE
> npm ERR! koavue2@1.0.0 start: `cross-env NODE_ENV=production node server`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the koavue2@1.0.0 start script 'cross-env NODE_ENV=production node server'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the koavue2 package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     cross-env NODE_ENV=production node server
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs koavue2
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls koavue2
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\github\vuekoassr\koa2vue2ssr\npm-debug.log

**Comment by i5ting** [comment]
已经测出问题了，是因为加了NODE_ENV product，马上修改

**Comment by wxsms** [comment]
请问问题修复了吗？

**Comment by base-stone** [comment]
修改个鬼啊

**Comment by leafront** [comment]
@i5ting 去你大爷的

**Comment by i5ting** [comment]
@leafront 提pr，当时只是写了demo
